university_project/departments/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "departments"

urlpatterns = [
    path('create/new/', views.CreateDepartment, name='create_department'),
    path('UIC/all/departments/', views.AllDepartments.as_view(), name='all_departments'),
    path('UIC/<faculty_slug>/edit/<department_slug>/', views.UpdateDepartment.as_view(), name='update_department'),
    path('UIC/<faculty_slug>/<department_slug>/', views.DepartmentDetail.as_view(), name='department_detail'),
    path('UIC/<faculty_slug>/department/<department_slug>/delete/', views.DepartmentDelete.as_view(), name='delete_department'),
    path('<department_slug>/students/', views.DepartmentStudents.as_view(), name='department_students'),
    path('<department_slug>/teachers/', views.DepartmentTeachers.as_view(), name='department_teachers'),
]

university_project/faculty/urls.py
from django.urls import path
from . import views



app_name = "faculties"


urlpatterns = [
    path('create/new/faculty/', views.CreateFaculty, name='create_faculty'),

    path('UIC/<faculty_slug>/edit/', views.UpdateFaculty.as_view(), name='update_faculty'),

    path('UIC/all/', views.FacultyList.as_view(), name='faculty_list'),
    path('UIC/<faculty_slug>/departments/', views.FacultyDetail.as_view(), name='faculty_detail'),
    path('UIC/<faculty_slug>/delete', views.FacultyDelete.as_view(), name='delete_faculty'),

    path('UIC/form/upload/images', views.facutyimages, name='gallery_form'),
    path('UIC/gallery/', views.ImageList.as_view(), name='varsity_images'),

]

university_project/students/urls.py
from django.urls import path, include
from . import views

app_name = 'students'

urlpatterns = [
    path('student/register/', views.student_register, name='student_register'),
    path('student/login/', views.student_login, name='student_login'),
    path('logout/', views.student_logout, name="student_logout"),

    path('change/<int:pk>/password/', views.change_password, name='change_password' ),
    path('<department_slug>/<student_slug>/profile/', views.StudentDetailView.as_view(), name='student_detail'),

    path('department/<department_slug>/students', views.StudentList.as_view(), name='student_list'),
    path('update/profile/student/<student_slug>/', views.AccountEditView.as_view(), name='update_student_profile'),
    path('delete/<department_slug>/student/<student_slug>/', views.StudentDeleteView.as_view(), name='delete_student'),

    path('all/students/', views.all_students.as_view(), name='all_students')
]

university_project/university_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from . views import ErrorTemplateView
# from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.AllFacultyList.as_view() , name='index'),

    path('registration/options/', views.RegistrationOptionsPage.as_view(), name='registration_options'),
    path('logout/', views.user_logout, name='logout'),
    path('thanks/', views.LogoutPage.as_view(), name='thanks'),

    path('user/login/', views.user_login, name='user_login'),
    path('faculties/', include("faculty.urls", namespace="faculties")),
    path('departments/', include("departments.urls", namespace='departments')),
    path('students/', include("students.urls", namespace='students')),
    path('teachers/', include("teachers.urls", namespace='teachers')),

    re_path(r"^.*$", ErrorTemplateView.as_view(), name='entry-point'),


]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

university_project/students/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
import markdown
from departments.models import Department


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    department = models.ForeignKey(Department, related_name="students", blank=False, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='students/profile_pics', blank=True)
    student_ID = models.CharField(max_length=20, unique=True, blank=False)
    student_slug = models.SlugField(allow_unicode=True, unique=True)
    session = models.CharField(max_length=9, blank=False)


    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        self.student_slug = slugify(self.user.username)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("students:student_detail",
                        kwargs={'department_slug': self.department.department_slug, "student_slug": self.student_slug})

    class Meta:
        ordering = ["student_ID"]
        unique_together = ["user", "department"]

university_project/students/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Student

class StudentForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    Confirm_Password = forms.CharField(label='confirm your password',widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(StudentForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("Confirm_Password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )


class StudentProfileInfoForm(forms.ModelForm):
    class Meta():
        model = Student
        fields = ('student_ID', 'session', 'department', 'profile_pic')

university_project/students/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.utils.text import slugify
from django.contrib.auth.models import User

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.views.generic import (TemplateView,ListView,View,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.utils.text import slugify

from .forms import StudentForm, StudentProfileInfoForm
from .models import Student
from departments.models import Department

@login_required
def student_logout(request):
    logout(request)
    return redirect('students:student_login')

def student_register(request):
    registered = False

    if request.method == 'POST':
        student_form = StudentForm(data=request.POST)
        student_profile_form = StudentProfileInfoForm(data=request.POST)

        if student_form.is_valid() and student_profile_form.is_valid():
            # Save User Form to Database
            user = student_form.save()

            # Hash the password
            user.set_password(user.password)
            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!
            # Can't commit yet because we still need to manipulate
            student_profile = student_profile_form.save(commit=False)
            # Set One to One relationship between
            # StudentForm and StudentProfileInfoForm
            student_profile.user = user

            if 'profile_pic' in request.FILES:
                student_profile.profile_pic = request.FILES['profile_pic']

            # now saving the model
            student_profile.save()
            registered = True

            name = request.POST.get('username')
            dept_id=request.POST.get('department')
            # get_object_or_404(Group,slug=self.kwargs.get("slug"))
            department = get_object_or_404(Department, pk=dept_id)
            from django.utils.text import slugify
            student_slug = slugify(name)
            dept_slug = slugify(department.name)
            # print("\n\n****department: {} and student: {}***/n/n".format(dept_slug, student_slug))

            return HttpResponseRedirect(reverse('students:student_detail', kwargs={'department_slug':dept_slug, 'student_slug':student_slug}))
        else:
            print(student_form.errors, student_profile_form.errors)
    else:
        student_form = StudentForm()
        student_profile_form = StudentProfileInfoForm()

    return render(request, "students/student_registration.html",context={
                    'student_form':student_form,
                    'student_profile_form':student_profile_form,
                    'registered':registered})


def student_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")

        else :
            print('Invalid Username: {} and password: {} is provided'.format(username, password))
            return HttpResponse("Invalid username or password supplied!")
    else:
        return render(request, 'students/login.html',{})


@login_required
def change_password(request):
    if request.mathod == 'POST':
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Your password is changed!")
            logout(request)
            return redirect('user_login')
        else:
            messages.error(request, "Please provide valid information")
    else:
        form = PasswordChangeForm(request, user)
    return render(request, 'students/change_password.html',{
                            'form':form})


class StudentDetailView(SelectRelatedMixin, DetailView):
    select_related = ("user", "department")
    context_object_name = 'student_detail'
    model = Student
    template_name = 'students/student_detail.html'

    def get_object(self):
        return get_object_or_404(
            Student,
            student_slug=self.kwargs['student_slug']
            # access_key=self.kwargs['access_key'],
        )


class StudentList(SelectRelatedMixin, ListView):
    model = Student
    select_related = ("user", "department")

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['slug'] = self.kwargs['slug']
    #     # context['current_month'] = self.current_month
    #     return context

from django.forms import ModelForm
@login_required
def StudentUpdate(request, student_slug):
    object = Student.objects.get(student_slug=student_slug)
    form = ModelForm(instance=object)

    return render(request, 'students/profileupdate_form.html', {'form':form})


from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory

class StudentUpdateView(InlineFormSetFactory):
    model = Student
    fields = ['profile_pic','department', 'session']

class AccountEditView(UpdateWithInlinesView):
    model = User
    old_password = []
    old_password.clear()
    fields = ['username', 'email', 'password']
    inlines = [StudentUpdateView,]
    template_name = 'students/profileupdate_form.html'

    def get_object(self):
        user = User.objects.get(pk=self.request.user.pk)
        self.old_password.append(user.password)
        return user

    def get_success_url(self):
        user1 = self.get_object()
        if self.old_password[1] == self.old_password[2]:
            print("no change passsword ",user1.password)
        else:
            user1.set_password(user1.password)

        user1.save()
        user1.student.save()

        self.old_password.clear()

        return get_object_or_404(
                    Student,
                    pk=user1.student.id
                ).get_absolute_url()




class StudentDeleteView(LoginRequiredMixin,SelectRelatedMixin, DeleteView):
    login_url = '/login/options/'
    # redirect_field_name = 'blog/post_detail.html'
    model = Student

    def get_object(self):
        return Student.objects.get(student_slug=self.kwargs['student_slug'])

    def get_success_url(self):
          # if you are passing 'slug' from 'urls' to 'DeleteView' for student
          # capture that 'slug' as dept_slug and pass it to 'reverse_lazy()' function
          dept_slug = self.kwargs['department_slug']
          student = self.get_object()
          user = student.user
          logout(self.request)
          user.delete()
          # self.StudentLogoutView()
          return reverse('departments:department_students', kwargs={
                                    'department_slug': dept_slug,})



class all_students(ListView):
    model = Student
    context_object_name = 'students'
    template_name = 'students/all_students.html'

university_project/students/templates/students/_student.html
<div class="media">

	<div class="media-body">
		<strong><a href="{% url 'students:student_detail' department_slug=student.department.department_slug student_slug=student.student_slug %}"> {{ student.user.username }}</a> </strong>

    <ol>
			<li> {{ student.user.username  }} </li>
      <li> {{ student.student_ID  }} </li>
      <li> {{ student.email  }} </li>
      <li> <a href="{% url 'departments:detail' faculty_slug=student.department.faculty.faculty_slug department_slug=student.department.department_slug %}">{{ student.department.name }}</a> </li>
      <li> <a href="{% url 'faculties:detail' faculty_slug=student.department.faculty.slug %}">{{ student.department.faculty.name }}</a> </li>
      <li> {{ student.session }} </li>
    </ol>


		<div class="media-footer">
			{% if user.is_superuser %}
				<a href="{% url 'students:student_delete' department_slug=student.department.department_slug student_slug=student.student_slug %}" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

university_project/students/templates/students/all_students.html
{% extends "faculties/faculty_base.html" %}

{% block content %}

  <div class="container jumbotron">

    <h3>All students are listed below</h3>
    <h6>Total students in UIT: <span style="font-size:22px;">{{students.count}}</span> </h6>
    <br>
    {# <h5> {{department.detail_html|safe}}</h4><br><br> #}

  </div>


  <div class="container">
    <section id="steps" class="steps section-bg" style="background-color:#fafcff">


      <hr>

      <table id="details_table" align="center">
        <thead style="color:blue">
          <th>Profile Pic</th>
          <th> <p>Student Username </p> </th>
          <th> <p>Student ID</p> </th>
          <th> <p>Email</p> </th>
          <th><p>Department</p> </th>
          <th> <p>Session </p> </th>
        </thead>
        <tr >
          <td class="extra-row"><br> </td>
          <td class="extra-row"><br> </td>
        </tr>

        {% for student in students %}
        <tr>
          {% if student.profile_pic %}
           <td><img src="{{ student.profile_pic.url }}"  height=120 width=120 alt=""></td>
          {% else %}
            <td><img src="/static/no_profile_pic.png"  height=120 width=120 alt=""></td>
          {% endif %}

          <td><p> <a href="{% url 'students:student_detail' department_slug=student.department.department_slug student_slug=student.student_slug %} " style="color:#1bac91; font-size:19px"> {{student.user.username}}</a> </h4></td>
          <td> {{ student.student_ID }} </td>

          {% if student.user.email %}
            <td><p> <span style="color:#2f5b9c;"> {{student.user.email}}</p></td>
          {% else %}
            <td><p> <span style="color:#2f5b9c;">Not given</p> </td>
          {% endif %}

          <td> {{ student.department.acronyms }} </td>
          <td><p> <span style="color:#2f5b9c;">{{student.session}}</p> </td>
        </tr>

        <tr >
          <td class="extra-row"><br> </td>
        </tr>
        <tr >
        </tr>
        {% endfor %}
      </table>

      <hr>

    </section>
  </div>

<br><br><br>

{% endblock %}

university_project/students/templates/students/change_password.html
{% extends "students/student_base.html" %}
{% load bootstrap4 %}
{% block content %}
<form class="" action="index.html" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}

  {{form}}

  {% buttons %}
    <button class="btn btn-primary" type="submit" name="button">Change Password</button>
  {% endbuttons %}
</form>

{% endblock %}

university_project/students/templates/students/profileupdate_form.html
{% extends "students/student_base.html" %}
{% load bootstrap4 %}

{% block content %}

<section id="steps" class="steps section-bg">
  <div class="container">
    <form  method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {% bootstrap_form form %}
    
      {% for formset in inlines %}
        <br>{{ formset.as_p }}<br>
      {% endfor %}
      <button class="btn btn-primary" type="submit" name="button">Update Profile</button>
      <br><br>
    </form>
  </div>
</section>

{% endblock %}

university_project/students/templates/students/student_base.html
{% extends "base.html" %}

{% block body_block %}
<br><br><br>

{% block content %}  {% endblock %}

{% endblock %}

university_project/students/templates/students/student_confirm_delete.html
{% extends "students/student_base.html" %}

{% block content %}

<div class="container jumbotron">
	<h3>Are you sure you want to delete your profile <a href="{% url 'students:student_detail' department_slug=student.department.department_slug student_slug=student.student_slug %}">
		({{object.user.username}})</a>?</h3><br><br>

	<form method="POST">
		{% csrf_token %}

		<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
		<a href="{% url 'students:student_detail' department_slug=student.department.department_slug student_slug=student.student_slug %}" class="btn btn-light btn-large">Cancel</a>

	</form>
</div>

{% endblock %}

university_project/students/templates/students/student_detail.html
{% extends "students/student_base.html" %}
{% block content %}
{% load static %}
<div class="container jumbotron">

<h1>Welcome to the Student Detail Page</h1><br><br>


<section id="portfolio" class="portfolio section-bg">

<div class="container">
  <div class="row portfolio-container" data-aos="fade-up">
    <div class="col-lg-4 col-md-6 portfolio-item filter-faculty">
      <div class="portfolio-wrap">
            {% if student_detail.profile_pic %}
             <img class="img-fluid" src="{{ student_detail.profile_pic.url }}" alt="">

             <div class="portfolio-info">
               <h4>{{ faculty.name }}</h4>

             <div class="portfolio-links">
               <h5><a href='{{ student_detail.profile_pic.url }}' title="More Details"><i class="bx bx-link"></i>Full Picture</a></h5>
             </div>

           </div>

            {% else %}
              <img class="img-fluid"  src="/static/no_profile_pic.png" alt="">
            {% endif %}

      </div>
    </div>

    <div class="col-lg-8 col-md-6 portfolio-item filter-faculty">
      <table id="details_table_teacher">
        <tr>
          <td> <p>Student Name: </p> </td>
          <td><p><span style="color:#2f5b9c;">{{student_detail.user.username}}</span></p> </td>
        </tr>

        <tr>
          <td> <p>Student ID: </td>
          <td> <span style="color:#2f5b9c;">{{student_detail.student_ID}}</span></p> </td>
        </tr>

        <tr>
          <td> <p>Email: </td>
          {% if student_detail.user.email %}
            <td><p> <span style="color:#2f5b9c;"> {{student_detail.user.email}}</span></p></td>
          {% else %}
            <td><p> <span style="color:#2f5b9c;">Not given</span></p> </td>
          {% endif %}
        </tr>

        <tr>
          <td> <p>Department:  </td>
          <td><span style="color:#2f5b9c;"><a href="{% url 'departments:department_detail' faculty_slug=student_detail.department.faculty.faculty_slug department_slug=student_detail.department.department_slug %}">{{student_detail.department}} </a> </span> </td>
        </tr>

        <tr>
          <td><p>Faculty: </td>
          <td> <span style="color:#2f5b9c;"><a href="{% url 'faculties:faculty_detail' faculty_slug=student_detail.department.faculty.faculty_slug %}">{{student_detail.department.faculty}}</a> </span></p></td>
        </tr>

        <tr>
          <td><p>Session: </p> </td>
          <td><p> <span style="color:#2f5b9c;">{{student_detail.session}}</p> </td>
        </tr>
      </table>


      </div>


    </div>

  </div>
</div>
</section>


{% if user.is_authenticated and user.username == student_detail.user.username %}
<div class="container">
  <a class='btn btn-warning' href="{% url 'students:update_student_profile' student_slug=student_detail.student_slug %}">
    <span class="fa fa-times-circle-ok"></span> Update Profile</a>
  <a class='btn btn-danger' href="{% url 'students:delete_student' department_slug=student_detail.department.department_slug student_slug=student_detail.student_slug %}">
    <span class="fa fa-times-circle-ok"></span> Delete Profile</a>

</div>
{% endif %}
<br><br>

{% endblock %}

university_project/students/templates/students/student_list.html
{% extends "students/student_base.html" %}
{% load humanize %}

{% block content %}


<div class="">
	{% for student in student_list %}
  {% include "students/_student.html" %}
	{% endfor %}
</div>


{% endblock %}

university_project/students/templates/students/student_registration.html
{% extends "students/student_base.html" %}
{# {% load staticfiles %} #}
{% load bootstrap4 %}

{% block content %}

  <div class="container">
    <div class="jumbotron">

      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}

        <h1>Register Here</h1>
        <h5>Student registration form</h3><br><br>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}

          {% bootstrap_form student_form %}
          {% bootstrap_form student_profile_form %}

          <br>
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

university_project/students/templates/students/studentprofileinfo_confirm_delete.html
{% extends "students/student_base.html" %}

{% block content %}
<h1>Delete {{student.user.username}}?</h1>

<form method="post">
  {% csrf_token %}

  <input type="submit" class="btn btn-danger" value="Delete">

  <a href="{% url 'departments:detail' slug1=student.students.slug slug2=student.slug %} ">Cancel</a>

</form>

{% endblock %}